plugins {
  id('java-gradle-plugin')
  alias(libs.plugins.spotless)
  alias(libs.plugins.publish)
}

version = '0.9.7'
group = 'io.github.tomaki19'

repositories {
  mavenCentral()
}

dependencies {
  testImplementation libs.junit
  testImplementation gradleTestKit()
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
  sourceCompatibility = JavaVersion.VERSION_17 // minimal java version supported by Gradle 9
}

spotless {
  java {
    licenseHeaderFile file('gradle/license-header.txt')
    removeUnusedImports()
  }
}

gradlePlugin {
  website = 'https://github.com/tomaki19/gradle-cmake-plugin'
  vcsUrl = 'https://github.com/tomaki19/gradle-cmake-plugin.git'
  plugins {
    cmake {
      id = "${project.group}.${project.name}"
      displayName = 'CMake Build Plugin'
      description = 'A Gradle plugin that uses the CMake build framework for C/C++ builds.'
      tags.set(['cmake', 'build', 'native', 'c', 'cpp', 'c++'])
      implementationClass = 'io.github.tomaki19.gradle.cmake.CMakePlugin'
    }
  }
}

tasks.named('test', Test) {
  useJUnitPlatform()
}

tasks.withType(Javadoc).configureEach {
  options.addStringOption('Xdoclint:-missing', '-quiet')
}

tasks.withType(AbstractPublishToMaven) {
  dependsOn check
}
