[versions]
publish-plugin = "2.1.1"
shadow-plugin = "9.4.1"
versions-plugin = "0.54.0"
spotless-plugin = "8.5.0"
jacocolog-plugin = "4.0.2"
spotbugs-plugin = "6.5.4"
spotbugs = "4.9.8"
mockito = "5.23.0"
freemarker = "2.3.34"

[libraries]
spotbugs = { module = "com.github.spotbugs:spotbugs", version.ref = "spotbugs" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
freemarker = { module = "org.freemarker:freemarker", version.ref = "freemarker" }

[bundles]
mockito = ["mockito-core", "mockito-junit-jupiter"]

[plugins]
publish = { id = "com.gradle.plugin-publish", version.ref = "publish-plugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow-plugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless-plugin" }
jacocolog = { id = "org.barfuin.gradle.jacocolog", version.ref = "jacocolog-plugin" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
